version: "3.8"

services:
  backend:
    build: ./Backend
    restart: unless-stopped
    container_name: backend_c
    env_file: ./.env
    ports:
      - 5000:5000
    networks:
      - app

  frontend:
    build:
      context: ./Frontend
      target: development
    container_name: frontend_c
    ports:
      - 3030:3000
    networks:
      - app
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules
    depends_on:
      - backend

volumes:
  db:

networks:
  app:
    driver: bridge
